export enum AuditSearchType {
	INPUT_OBJECT_KEY = 'INPUT_OBJECT_KEY',
	OUTPUT_OBJECT_KEY = 'OUTPUT_OBJECT_KEY', // not supported on redshift
	RAW_FILE_NAME = 'RAW_FILE_NAME',
	SHORT_ERROR_MESSAGE = 'SHORT_ERROR_MESSAGE'
}
