export enum ChartType {
	ORDERS_PLACED = 'ORDERS_PLACED',
	NET_SALES = 'NET_SALES',
	TOTAL_BUYERS = 'TOTAL_BUYERS',
	REPEAT_BUYERS = 'REPEAT_BUYERS',
	NEW_BUYERS = 'NEW_BUYERS',
	GUEST_BUYERS = 'GUEST_BUYERS',
	TOTAL_VISITORS = 'TOTAL_VISITORS',
	NEW_REGISTRATIONS = 'NEW_REGISTRATIONS',
	CANCELLED_FAILED = 'CANCELLED_FAILED',
	KYB_REJECTED = 'KYB_REJECTED',
	RISK_REJECTED = 'RISK_REJECTED',
	PAYMENT_AUTH_FAILED = 'PAYMENT_AUTH_FAILED',
	FULFILLMENT_FAILED = 'FULFILLMENT_FAILED',
	REFUNDS_CHARGEBACK = 'REFUNDS_CHARGEBACK',
	REFUNDS = 'REFUNDS',
	CHARGEBACK = 'CHARGEBACK'
}

export namespace ChartType {
	export function values(): ChartType[] {
		return [
			ChartType.ORDERS_PLACED,
			ChartType.NET_SALES,
			ChartType.TOTAL_BUYERS,
			ChartType.REPEAT_BUYERS,
			ChartType.NEW_BUYERS,
			ChartType.GUEST_BUYERS,
			ChartType.TOTAL_VISITORS,
			ChartType.NEW_REGISTRATIONS,
			ChartType.CANCELLED_FAILED,
			ChartType.KYB_REJECTED,
			ChartType.RISK_REJECTED,
			ChartType.PAYMENT_AUTH_FAILED,
			ChartType.FULFILLMENT_FAILED,
			ChartType.REFUNDS_CHARGEBACK,
			ChartType.REFUNDS,
			ChartType.CHARGEBACK
		];
	}
}
