export enum PipelinePageType {
	REAL_TIME_DATA_TRANSFER = 'REAL_TIME_DATA_TRANSFER',
	REAL_TIME_REDSHIFT_DATA_COPY = 'REAL_TIME_REDSHIFT_DATA_COPY',
	BATCH_BATCH = 'BATCH_BATCH',
	BATCH_DATA_TRANSFER = 'BATCH_DATA_TRANSFER',
	BATCH_REDSHIFT_DATA_COPY = 'BATCH_REDSHIFT_DATA_COPY',
	HISTORICAL_REAL_TIME_REDSHIFT_DATA_COPY = 'HISTORICAL_REAL_TIME_REDSHIFT_DATA_COPY',
	HISTORICAL_BATCH_BATCH = 'HISTORICAL_BATCH_BATCH',
	HISTORICAL_BATCH_DATA_TRANSFER = 'HISTORICAL_BATCH_DATA_TRANSFER',
	HISTORICAL_BATCH_REDSHIFT_DATA_COPY = 'HISTORICAL_BATCH_REDSHIFT_DATA_COPY'
}
